package com.shampaggon.crackshot;

import java.util.*;
import org.bukkit.*;

public class SoundManager
{
    private static Map<String, String[]> sounds;
    
    static {
        (SoundManager.sounds = new HashMap<String, String[]>()).put("AMBIENCE_CAVE", new String[] { "AMBIENT_CAVE" });
        SoundManager.sounds.put("AMBIENT_CAVE", new String[] { "AMBIENCE_CAVE" });
        SoundManager.sounds.put("AMBIENCE_RAIN", new String[] { "WEATHER_RAIN" });
        SoundManager.sounds.put("WEATHER_RAIN", new String[] { "AMBIENCE_RAIN" });
        SoundManager.sounds.put("AMBIENCE_THUNDER", new String[] { "ENTITY_LIGHTNING_THUNDER", "ENTITY_LIGHTNING_BOLT_THUNDER" });
        SoundManager.sounds.put("ENTITY_LIGHTNING_THUNDER", new String[] { "AMBIENCE_THUNDER", "ENTITY_LIGHTNING_BOLT_THUNDER" });
        SoundManager.sounds.put("ENTITY_LIGHTNING_BOLT_THUNDER", new String[] { "AMBIENCE_THUNDER", "ENTITY_LIGHTNING_THUNDER" });
        SoundManager.sounds.put("ANVIL_BREAK", new String[] { "BLOCK_ANVIL_BREAK" });
        SoundManager.sounds.put("BLOCK_ANVIL_BREAK", new String[] { "ANVIL_BREAK" });
        SoundManager.sounds.put("ANVIL_LAND", new String[] { "BLOCK_ANVIL_LAND" });
        SoundManager.sounds.put("BLOCK_ANVIL_LAND", new String[] { "ANVIL_LAND" });
        SoundManager.sounds.put("ANVIL_USE", new String[] { "BLOCK_ANVIL_USE" });
        SoundManager.sounds.put("BLOCK_ANVIL_USE", new String[] { "ANVIL_USE" });
        SoundManager.sounds.put("ARROW_HIT", new String[] { "ENTITY_ARROW_HIT" });
        SoundManager.sounds.put("ENTITY_ARROW_HIT", new String[] { "ARROW_HIT" });
        SoundManager.sounds.put("BURP", new String[] { "ENTITY_PLAYER_BURP" });
        SoundManager.sounds.put("ENTITY_PLAYER_BURP", new String[] { "BURP" });
        SoundManager.sounds.put("CHEST_CLOSE", new String[] { "ENTITY_CHEST_CLOSE", "BLOCK_CHEST_CLOSE" });
        SoundManager.sounds.put("ENTITY_CHEST_CLOSE", new String[] { "CHEST_CLOSE", "BLOCK_CHEST_CLOSE" });
        SoundManager.sounds.put("BLOCK_CHEST_CLOSE", new String[] { "CHEST_CLOSE", "ENTITY_CHEST_CLOSE" });
        SoundManager.sounds.put("CHEST_OPEN", new String[] { "ENTITY_CHEST_OPEN", "BLOCK_CHEST_OPEN" });
        SoundManager.sounds.put("ENTITY_CHEST_OPEN", new String[] { "CHEST_OPEN", "BLOCK_CHEST_OPEN" });
        SoundManager.sounds.put("BLOCK_CHEST_OPEN", new String[] { "CHEST_OPEN", "ENTITY_CHEST_OPEN" });
        SoundManager.sounds.put("CLICK", new String[] { "UI_BUTTON_CLICK" });
        SoundManager.sounds.put("UI_BUTTON_CLICK", new String[] { "CLICK" });
        SoundManager.sounds.put("DOOR_CLOSE", new String[] { "BLOCK_WOODEN_DOOR_CLOSE" });
        SoundManager.sounds.put("BLOCK_WOODEN_DOOR_CLOSE", new String[] { "DOOR_CLOSE" });
        SoundManager.sounds.put("DOOR_OPEN", new String[] { "BLOCK_WOODEN_DOOR_OPEN" });
        SoundManager.sounds.put("BLOCK_WOODEN_DOOR_OPEN", new String[] { "DOOR_OPEN" });
        SoundManager.sounds.put("DRINK", new String[] { "ENTITY_GENERIC_DRINK" });
        SoundManager.sounds.put("ENTITY_GENERIC_DRINK", new String[] { "DRINK" });
        SoundManager.sounds.put("EAT", new String[] { "ENTITY_GENERIC_EAT" });
        SoundManager.sounds.put("ENTITY_GENERIC_EAT", new String[] { "EAT" });
        SoundManager.sounds.put("EXPLODE", new String[] { "ENTITY_GENERIC_EXPLODE" });
        SoundManager.sounds.put("ENTITY_GENERIC_EXPLODE", new String[] { "EXPLODE" });
        SoundManager.sounds.put("FALL_BIG", new String[] { "ENTITY_GENERIC_BIG_FALL" });
        SoundManager.sounds.put("ENTITY_GENERIC_BIG_FALL", new String[] { "FALL_BIG" });
        SoundManager.sounds.put("FALL_SMALL", new String[] { "ENTITY_GENERIC_SMALL_FALL" });
        SoundManager.sounds.put("ENTITY_GENERIC_SMALL_FALL", new String[] { "FALL_SMALL" });
        SoundManager.sounds.put("FIRE", new String[] { "BLOCK_FIRE_AMBIENT" });
        SoundManager.sounds.put("BLOCK_FIRE_AMBIENT", new String[] { "FIRE" });
        SoundManager.sounds.put("FIRE_IGNITE", new String[] { "ITEM_FLINTANDSTEEL_USE" });
        SoundManager.sounds.put("ITEM_FLINTANDSTEEL_USE", new String[] { "FIRE_IGNITE" });
        SoundManager.sounds.put("FIZZ", new String[] { "BLOCK_FIRE_EXTINGUISH" });
        SoundManager.sounds.put("BLOCK_FIRE_EXTINGUISH", new String[] { "FIZZ" });
        SoundManager.sounds.put("FUSE", new String[] { "ENTITY_TNT_PRIMED" });
        SoundManager.sounds.put("ENTITY_TNT_PRIMED", new String[] { "FUSE" });
        SoundManager.sounds.put("GLASS", new String[] { "BLOCK_GLASS_BREAK" });
        SoundManager.sounds.put("BLOCK_GLASS_BREAK", new String[] { "GLASS" });
        SoundManager.sounds.put("HURT_FLESH", new String[] { "ENTITY_PLAYER_HURT" });
        SoundManager.sounds.put("ENTITY_PLAYER_HURT", new String[] { "HURT_FLESH" });
        SoundManager.sounds.put("ITEM_BREAK", new String[] { "ENTITY_ITEM_BREAK" });
        SoundManager.sounds.put("ENTITY_ITEM_BREAK", new String[] { "ITEM_BREAK" });
        SoundManager.sounds.put("ITEM_PICKUP", new String[] { "ENTITY_ITEM_PICKUP" });
        SoundManager.sounds.put("ENTITY_ITEM_PICKUP", new String[] { "ITEM_PICKUP" });
        SoundManager.sounds.put("LAVA", new String[] { "BLOCK_LAVA_AMBIENT" });
        SoundManager.sounds.put("BLOCK_LAVA_AMBIENT", new String[] { "LAVA" });
        SoundManager.sounds.put("LAVA_POP", new String[] { "BLOCK_LAVA_POP" });
        SoundManager.sounds.put("BLOCK_LAVA_POP", new String[] { "LAVA_POP" });
        SoundManager.sounds.put("LEVEL_UP", new String[] { "ENTITY_PLAYER_LEVELUP" });
        SoundManager.sounds.put("ENTITY_PLAYER_LEVELUP", new String[] { "LEVEL_UP" });
        SoundManager.sounds.put("MINECART_BASE", new String[] { "ENTITY_MINECART_RIDING" });
        SoundManager.sounds.put("ENTITY_MINECART_RIDING", new String[] { "MINECART_BASE" });
        SoundManager.sounds.put("MINECART_INSIDE", new String[] { "ENTITY_MINECART_RIDING" });
        SoundManager.sounds.put("ENTITY_MINECART_RIDING", new String[] { "MINECART_INSIDE" });
        SoundManager.sounds.put("NOTE_BASS", new String[] { "BLOCK_NOTE_BASS", "BLOCK_NOTE_BLOCK_BASS" });
        SoundManager.sounds.put("BLOCK_NOTE_BASS", new String[] { "NOTE_BASS", "BLOCK_NOTE_BLOCK_BASS" });
        SoundManager.sounds.put("BLOCK_NOTE_BLOCK_BASS", new String[] { "NOTE_BASS", "BLOCK_NOTE_BASS" });
        SoundManager.sounds.put("NOTE_PIANO", new String[] { "BLOCK_NOTE_HARP", "BLOCK_NOTE_BLOCK_HARP" });
        SoundManager.sounds.put("BLOCK_NOTE_HARP", new String[] { "NOTE_PIANO", "BLOCK_NOTE_BLOCK_HARP" });
        SoundManager.sounds.put("BLOCK_NOTE_BLOCK_HARP", new String[] { "NOTE_PIANO", "BLOCK_NOTE_HARP" });
        SoundManager.sounds.put("NOTE_BASS_DRUM", new String[] { "BLOCK_NOTE_BASEDRUM", "BLOCK_NOTE_BLOCK_BASEDRUM" });
        SoundManager.sounds.put("BLOCK_NOTE_BASEDRUM", new String[] { "NOTE_BASS_DRUM", "BLOCK_NOTE_BLOCK_BASEDRUM" });
        SoundManager.sounds.put("BLOCK_NOTE_BLOCK_BASEDRUM", new String[] { "NOTE_BASS_DRUM", "BLOCK_NOTE_BASEDRUM" });
        SoundManager.sounds.put("NOTE_STICKS", new String[] { "BLOCK_NOTE_HAT", "BLOCK_NOTE_BLOCK_HAT" });
        SoundManager.sounds.put("BLOCK_NOTE_HAT", new String[] { "NOTE_STICKS", "BLOCK_NOTE_BLOCK_HAT" });
        SoundManager.sounds.put("BLOCK_NOTE_BLOCK_HAT", new String[] { "NOTE_STICKS", "BLOCK_NOTE_HAT" });
        SoundManager.sounds.put("NOTE_BASS_GUITAR", new String[] { "BLOCK_NOTE_GUITAR", "BLOCK_NOTE_BLOCK_GUITAR", "BLOCK_NOTE_BASS" });
        SoundManager.sounds.put("BLOCK_NOTE_GUITAR", new String[] { "NOTE_BASS_GUITAR", "BLOCK_NOTE_BLOCK_GUITAR", "BLOCK_NOTE_BASS" });
        SoundManager.sounds.put("BLOCK_NOTE_BLOCK_GUITAR", new String[] { "NOTE_BASS_GUITAR", "BLOCK_NOTE_GUITAR", "BLOCK_NOTE_BASS" });
        SoundManager.sounds.put("BLOCK_NOTE_BASS", new String[] { "NOTE_BASS_GUITAR", "BLOCK_NOTE_GUITAR", "BLOCK_NOTE_BLOCK_GUITAR" });
        SoundManager.sounds.put("NOTE_SNARE_DRUM", new String[] { "BLOCK_NOTE_SNARE", "BLOCK_NOTE_BLOCK_SNARE" });
        SoundManager.sounds.put("BLOCK_NOTE_SNARE", new String[] { "NOTE_SNARE_DRUM", "BLOCK_NOTE_BLOCK_SNARE" });
        SoundManager.sounds.put("BLOCK_NOTE_BLOCK_SNARE", new String[] { "NOTE_SNARE_DRUM", "BLOCK_NOTE_SNARE" });
        SoundManager.sounds.put("NOTE_PLING", new String[] { "BLOCK_NOTE_PLING", "BLOCK_NOTE_BLOCK_PLING" });
        SoundManager.sounds.put("BLOCK_NOTE_PLING", new String[] { "NOTE_PLING", "BLOCK_NOTE_BLOCK_PLING" });
        SoundManager.sounds.put("BLOCK_NOTE_BLOCK_PLING", new String[] { "NOTE_PLING", "BLOCK_NOTE_PLING" });
        SoundManager.sounds.put("ORB_PICKUP", new String[] { "ENTITY_EXPERIENCE_ORB_PICKUP" });
        SoundManager.sounds.put("ENTITY_EXPERIENCE_ORB_PICKUP", new String[] { "ORB_PICKUP" });
        SoundManager.sounds.put("PISTON_EXTEND", new String[] { "BLOCK_PISTON_EXTEND" });
        SoundManager.sounds.put("BLOCK_PISTON_EXTEND", new String[] { "PISTON_EXTEND" });
        SoundManager.sounds.put("PISTON_RETRACT", new String[] { "BLOCK_PISTON_CONTRACT" });
        SoundManager.sounds.put("BLOCK_PISTON_CONTRACT", new String[] { "PISTON_RETRACT" });
        SoundManager.sounds.put("PORTAL", new String[] { "BLOCK_PORTAL_AMBIENT" });
        SoundManager.sounds.put("BLOCK_PORTAL_AMBIENT", new String[] { "PORTAL" });
        SoundManager.sounds.put("PORTAL_TRAVEL", new String[] { "BLOCK_PORTAL_TRAVEL" });
        SoundManager.sounds.put("BLOCK_PORTAL_TRAVEL", new String[] { "PORTAL_TRAVEL" });
        SoundManager.sounds.put("PORTAL_TRIGGER", new String[] { "BLOCK_PORTAL_TRIGGER" });
        SoundManager.sounds.put("BLOCK_PORTAL_TRIGGER", new String[] { "PORTAL_TRIGGER" });
        SoundManager.sounds.put("SHOOT_ARROW", new String[] { "ENTITY_ARROW_SHOOT" });
        SoundManager.sounds.put("ENTITY_ARROW_SHOOT", new String[] { "SHOOT_ARROW" });
        SoundManager.sounds.put("SPLASH", new String[] { "ENTITY_GENERIC_SPLASH" });
        SoundManager.sounds.put("ENTITY_GENERIC_SPLASH", new String[] { "SPLASH" });
        SoundManager.sounds.put("SPLASH2", new String[] { "ENTITY_BOBBER_SPLASH", "ENTITY_FISHING_BOBBER_SPLASH" });
        SoundManager.sounds.put("ENTITY_BOBBER_SPLASH", new String[] { "SPLASH2", "ENTITY_FISHING_BOBBER_SPLASH" });
        SoundManager.sounds.put("ENTITY_FISHING_BOBBER_SPLASH", new String[] { "SPLASH2", "ENTITY_BOBBER_SPLASH" });
        SoundManager.sounds.put("STEP_GRASS", new String[] { "BLOCK_GRASS_STEP" });
        SoundManager.sounds.put("BLOCK_GRASS_STEP", new String[] { "STEP_GRASS" });
        SoundManager.sounds.put("STEP_GRAVEL", new String[] { "BLOCK_GRAVEL_STEP" });
        SoundManager.sounds.put("BLOCK_GRAVEL_STEP", new String[] { "STEP_GRAVEL" });
        SoundManager.sounds.put("STEP_LADDER", new String[] { "BLOCK_LADDER_STEP" });
        SoundManager.sounds.put("BLOCK_LADDER_STEP", new String[] { "STEP_LADDER" });
        SoundManager.sounds.put("STEP_SAND", new String[] { "BLOCK_SAND_STEP" });
        SoundManager.sounds.put("BLOCK_SAND_STEP", new String[] { "STEP_SAND" });
        SoundManager.sounds.put("STEP_SNOW", new String[] { "BLOCK_SNOW_STEP" });
        SoundManager.sounds.put("BLOCK_SNOW_STEP", new String[] { "STEP_SNOW" });
        SoundManager.sounds.put("STEP_STONE", new String[] { "BLOCK_STONE_STEP" });
        SoundManager.sounds.put("BLOCK_STONE_STEP", new String[] { "STEP_STONE" });
        SoundManager.sounds.put("STEP_WOOD", new String[] { "BLOCK_WOOD_STEP" });
        SoundManager.sounds.put("BLOCK_WOOD_STEP", new String[] { "STEP_WOOD" });
        SoundManager.sounds.put("STEP_WOOL", new String[] { "BLOCK_CLOTH_STEP", "BLOCK_WOOL_STEP" });
        SoundManager.sounds.put("BLOCK_CLOTH_STEP", new String[] { "STEP_WOOL", "BLOCK_WOOL_STEP" });
        SoundManager.sounds.put("BLOCK_WOOL_STEP", new String[] { "STEP_WOOL", "BLOCK_CLOTH_STEP" });
        SoundManager.sounds.put("SWIM", new String[] { "ENTITY_GENERIC_SWIM" });
        SoundManager.sounds.put("ENTITY_GENERIC_SWIM", new String[] { "SWIM" });
        SoundManager.sounds.put("WATER", new String[] { "BLOCK_WATER_AMBIENT" });
        SoundManager.sounds.put("BLOCK_WATER_AMBIENT", new String[] { "WATER" });
        SoundManager.sounds.put("WOOD_CLICK", new String[] { "BLOCK_WOOD_BUTTON_CLICK_ON", "BLOCK_WOODEN_BUTTON_CLICK_ON" });
        SoundManager.sounds.put("BLOCK_WOOD_BUTTON_CLICK_ON", new String[] { "WOOD_CLICK", "BLOCK_WOODEN_BUTTON_CLICK_ON" });
        SoundManager.sounds.put("BLOCK_WOODEN_BUTTON_CLICK_ON", new String[] { "WOOD_CLICK", "BLOCK_WOOD_BUTTON_CLICK_ON" });
        SoundManager.sounds.put("BAT_DEATH", new String[] { "ENTITY_BAT_DEATH" });
        SoundManager.sounds.put("ENTITY_BAT_DEATH", new String[] { "BAT_DEATH" });
        SoundManager.sounds.put("BAT_HURT", new String[] { "ENTITY_BAT_HURT" });
        SoundManager.sounds.put("ENTITY_BAT_HURT", new String[] { "BAT_HURT" });
        SoundManager.sounds.put("BAT_IDLE", new String[] { "ENTITY_BAT_AMBIENT" });
        SoundManager.sounds.put("ENTITY_BAT_AMBIENT", new String[] { "BAT_IDLE" });
        SoundManager.sounds.put("BAT_LOOP", new String[] { "ENTITY_BAT_LOOP" });
        SoundManager.sounds.put("ENTITY_BAT_LOOP", new String[] { "BAT_LOOP" });
        SoundManager.sounds.put("BAT_TAKEOFF", new String[] { "ENTITY_BAT_TAKEOFF" });
        SoundManager.sounds.put("ENTITY_BAT_TAKEOFF", new String[] { "BAT_TAKEOFF" });
        SoundManager.sounds.put("BLAZE_BREATH", new String[] { "ENTITY_BLAZE_AMBIENT" });
        SoundManager.sounds.put("ENTITY_BLAZE_AMBIENT", new String[] { "BLAZE_BREATH" });
        SoundManager.sounds.put("BLAZE_DEATH", new String[] { "ENTITY_BLAZE_DEATH" });
        SoundManager.sounds.put("ENTITY_BLAZE_DEATH", new String[] { "BLAZE_DEATH" });
        SoundManager.sounds.put("BLAZE_HIT", new String[] { "ENTITY_BLAZE_HURT" });
        SoundManager.sounds.put("ENTITY_BLAZE_HURT", new String[] { "BLAZE_HIT" });
        SoundManager.sounds.put("CAT_HISS", new String[] { "ENTITY_CAT_HISS" });
        SoundManager.sounds.put("ENTITY_CAT_HISS", new String[] { "CAT_HISS" });
        SoundManager.sounds.put("CAT_HIT", new String[] { "ENTITY_CAT_HURT" });
        SoundManager.sounds.put("ENTITY_CAT_HURT", new String[] { "CAT_HIT" });
        SoundManager.sounds.put("CAT_MEOW", new String[] { "ENTITY_CAT_AMBIENT" });
        SoundManager.sounds.put("ENTITY_CAT_AMBIENT", new String[] { "CAT_MEOW" });
        SoundManager.sounds.put("CAT_PURR", new String[] { "ENTITY_CAT_PURR" });
        SoundManager.sounds.put("ENTITY_CAT_PURR", new String[] { "CAT_PURR" });
        SoundManager.sounds.put("CAT_PURREOW", new String[] { "ENTITY_CAT_PURREOW" });
        SoundManager.sounds.put("ENTITY_CAT_PURREOW", new String[] { "CAT_PURREOW" });
        SoundManager.sounds.put("CHICKEN_IDLE", new String[] { "ENTITY_CHICKEN_AMBIENT" });
        SoundManager.sounds.put("ENTITY_CHICKEN_AMBIENT", new String[] { "CHICKEN_IDLE" });
        SoundManager.sounds.put("CHICKEN_HURT", new String[] { "ENTITY_CHICKEN_HURT" });
        SoundManager.sounds.put("ENTITY_CHICKEN_HURT", new String[] { "CHICKEN_HURT" });
        SoundManager.sounds.put("CHICKEN_EGG_POP", new String[] { "ENTITY_CHICKEN_EGG" });
        SoundManager.sounds.put("ENTITY_CHICKEN_EGG", new String[] { "CHICKEN_EGG_POP" });
        SoundManager.sounds.put("CHICKEN_WALK", new String[] { "ENTITY_CHICKEN_STEP" });
        SoundManager.sounds.put("ENTITY_CHICKEN_STEP", new String[] { "CHICKEN_WALK" });
        SoundManager.sounds.put("COW_IDLE", new String[] { "ENTITY_COW_AMBIENT" });
        SoundManager.sounds.put("ENTITY_COW_AMBIENT", new String[] { "COW_IDLE" });
        SoundManager.sounds.put("COW_HURT", new String[] { "ENTITY_COW_HURT" });
        SoundManager.sounds.put("ENTITY_COW_HURT", new String[] { "COW_HURT" });
        SoundManager.sounds.put("COW_WALK", new String[] { "ENTITY_COW_STEP" });
        SoundManager.sounds.put("ENTITY_COW_STEP", new String[] { "COW_WALK" });
        SoundManager.sounds.put("CREEPER_HISS", new String[] { "ENTITY_CREEPER_PRIMED" });
        SoundManager.sounds.put("ENTITY_CREEPER_PRIMED", new String[] { "CREEPER_HISS" });
        SoundManager.sounds.put("CREEPER_DEATH", new String[] { "ENTITY_CREEPER_DEATH" });
        SoundManager.sounds.put("ENTITY_CREEPER_DEATH", new String[] { "CREEPER_DEATH" });
        SoundManager.sounds.put("ENDERDRAGON_DEATH", new String[] { "ENTITY_ENDERDRAGON_DEATH", "ENTITY_ENDER_DRAGON_DEATH" });
        SoundManager.sounds.put("ENTITY_ENDERDRAGON_DEATH", new String[] { "ENDERDRAGON_DEATH", "ENTITY_ENDER_DRAGON_DEATH" });
        SoundManager.sounds.put("ENTITY_ENDER_DRAGON_DEATH", new String[] { "ENDERDRAGON_DEATH", "ENTITY_ENDERDRAGON_DEATH" });
        SoundManager.sounds.put("ENDERDRAGON_GROWL", new String[] { "ENTITY_ENDERDRAGON_GROWL", "ENTITY_ENDER_DRAGON_GROWL" });
        SoundManager.sounds.put("ENTITY_ENDERDRAGON_GROWL", new String[] { "ENDERDRAGON_GROWL", "ENTITY_ENDER_DRAGON_GROWL" });
        SoundManager.sounds.put("ENTITY_ENDER_DRAGON_GROWL", new String[] { "ENDERDRAGON_GROWL", "ENTITY_ENDERDRAGON_GROWL" });
        SoundManager.sounds.put("ENDERDRAGON_HIT", new String[] { "ENTITY_ENDERDRAGON_HURT", "ENTITY_ENDER_DRAGON_HURT" });
        SoundManager.sounds.put("ENTITY_ENDERDRAGON_HURT", new String[] { "ENDERDRAGON_HIT", "ENTITY_ENDER_DRAGON_HURT" });
        SoundManager.sounds.put("ENTITY_ENDER_DRAGON_HURT", new String[] { "ENDERDRAGON_HIT", "ENTITY_ENDERDRAGON_HURT" });
        SoundManager.sounds.put("ENDERDRAGON_WINGS", new String[] { "ENTITY_ENDERDRAGON_FLAP", "ENTITY_ENDER_DRAGON_FLAP" });
        SoundManager.sounds.put("ENTITY_ENDERDRAGON_FLAP", new String[] { "ENDERDRAGON_WINGS", "ENTITY_ENDER_DRAGON_FLAP" });
        SoundManager.sounds.put("ENTITY_ENDER_DRAGON_FLAP", new String[] { "ENDERDRAGON_WINGS", "ENTITY_ENDERDRAGON_FLAP" });
        SoundManager.sounds.put("ENDERMAN_DEATH", new String[] { "ENTITY_ENDERMEN_DEATH", "ENTITY_ENDERMAN_DEATH" });
        SoundManager.sounds.put("ENTITY_ENDERMEN_DEATH", new String[] { "ENDERMAN_DEATH", "ENTITY_ENDERMAN_DEATH" });
        SoundManager.sounds.put("ENTITY_ENDERMAN_DEATH", new String[] { "ENDERMAN_DEATH", "ENTITY_ENDERMEN_DEATH" });
        SoundManager.sounds.put("ENDERMAN_HIT", new String[] { "ENTITY_ENDERMEN_HURT", "ENTITY_ENDERMAN_HURT" });
        SoundManager.sounds.put("ENTITY_ENDERMEN_HURT", new String[] { "ENDERMAN_HIT", "ENTITY_ENDERMAN_HURT" });
        SoundManager.sounds.put("ENTITY_ENDERMAN_HURT", new String[] { "ENDERMAN_HIT", "ENTITY_ENDERMEN_HURT" });
        SoundManager.sounds.put("ENDERMAN_IDLE", new String[] { "ENTITY_ENDERMEN_AMBIENT", "ENTITY_ENDERMAN_AMBIENT" });
        SoundManager.sounds.put("ENTITY_ENDERMEN_AMBIENT", new String[] { "ENDERMAN_IDLE", "ENTITY_ENDERMAN_AMBIENT" });
        SoundManager.sounds.put("ENTITY_ENDERMAN_AMBIENT", new String[] { "ENDERMAN_IDLE", "ENTITY_ENDERMEN_AMBIENT" });
        SoundManager.sounds.put("ENDERMAN_TELEPORT", new String[] { "ENTITY_ENDERMEN_TELEPORT", "ENTITY_ENDERMAN_TELEPORT" });
        SoundManager.sounds.put("ENTITY_ENDERMEN_TELEPORT", new String[] { "ENDERMAN_TELEPORT", "ENTITY_ENDERMAN_TELEPORT" });
        SoundManager.sounds.put("ENTITY_ENDERMAN_TELEPORT", new String[] { "ENDERMAN_TELEPORT", "ENTITY_ENDERMEN_TELEPORT" });
        SoundManager.sounds.put("ENDERMAN_SCREAM", new String[] { "ENTITY_ENDERMEN_SCREAM", "ENTITY_ENDERMAN_SCREAM" });
        SoundManager.sounds.put("ENTITY_ENDERMEN_SCREAM", new String[] { "ENDERMAN_SCREAM", "ENTITY_ENDERMAN_SCREAM" });
        SoundManager.sounds.put("ENTITY_ENDERMAN_SCREAM", new String[] { "ENDERMAN_SCREAM", "ENTITY_ENDERMEN_SCREAM" });
        SoundManager.sounds.put("ENDERMAN_STARE", new String[] { "ENTITY_ENDERMEN_STARE", "ENTITY_ENDERMAN_STARE" });
        SoundManager.sounds.put("ENTITY_ENDERMEN_STARE", new String[] { "ENDERMAN_STARE", "ENTITY_ENDERMAN_STARE" });
        SoundManager.sounds.put("ENTITY_ENDERMAN_STARE", new String[] { "ENDERMAN_STARE", "ENTITY_ENDERMEN_STARE" });
        SoundManager.sounds.put("GHAST_SCREAM", new String[] { "ENTITY_GHAST_SCREAM" });
        SoundManager.sounds.put("ENTITY_GHAST_SCREAM", new String[] { "GHAST_SCREAM" });
        SoundManager.sounds.put("GHAST_SCREAM2", new String[] { "ENTITY_GHAST_HURT" });
        SoundManager.sounds.put("ENTITY_GHAST_HURT", new String[] { "GHAST_SCREAM2" });
        SoundManager.sounds.put("GHAST_CHARGE", new String[] { "ENTITY_GHAST_WARN" });
        SoundManager.sounds.put("ENTITY_GHAST_WARN", new String[] { "GHAST_CHARGE" });
        SoundManager.sounds.put("GHAST_DEATH", new String[] { "ENTITY_GHAST_DEATH" });
        SoundManager.sounds.put("ENTITY_GHAST_DEATH", new String[] { "GHAST_DEATH" });
        SoundManager.sounds.put("GHAST_FIREBALL", new String[] { "ENTITY_GHAST_SHOOT" });
        SoundManager.sounds.put("ENTITY_GHAST_SHOOT", new String[] { "GHAST_FIREBALL" });
        SoundManager.sounds.put("GHAST_MOAN", new String[] { "ENTITY_GHAST_AMBIENT" });
        SoundManager.sounds.put("ENTITY_GHAST_AMBIENT", new String[] { "GHAST_MOAN" });
        SoundManager.sounds.put("IRONGOLEM_THROW", new String[] { "ENTITY_IRONGOLEM_ATTACK", "ENTITY_IRON_GOLEM_ATTACK" });
        SoundManager.sounds.put("ENTITY_IRONGOLEM_ATTACK", new String[] { "IRONGOLEM_THROW", "ENTITY_IRON_GOLEM_ATTACK" });
        SoundManager.sounds.put("ENTITY_IRON_GOLEM_ATTACK", new String[] { "IRONGOLEM_THROW", "ENTITY_IRONGOLEM_ATTACK" });
        SoundManager.sounds.put("IRONGOLEM_DEATH", new String[] { "ENTITY_IRONGOLEM_DEATH", "ENTITY_IRON_GOLEM_DEATH" });
        SoundManager.sounds.put("ENTITY_IRONGOLEM_DEATH", new String[] { "IRONGOLEM_DEATH", "ENTITY_IRON_GOLEM_DEATH" });
        SoundManager.sounds.put("ENTITY_IRON_GOLEM_DEATH", new String[] { "IRONGOLEM_DEATH", "ENTITY_IRONGOLEM_DEATH" });
        SoundManager.sounds.put("IRONGOLEM_HIT", new String[] { "ENTITY_IRONGOLEM_HURT", "ENTITY_IRON_GOLEM_HURT" });
        SoundManager.sounds.put("ENTITY_IRONGOLEM_HURT", new String[] { "IRONGOLEM_HIT", "ENTITY_IRON_GOLEM_HURT" });
        SoundManager.sounds.put("ENTITY_IRON_GOLEM_HURT", new String[] { "IRONGOLEM_HIT", "ENTITY_IRONGOLEM_HURT" });
        SoundManager.sounds.put("IRONGOLEM_WALK", new String[] { "ENTITY_IRONGOLEM_STEP", "ENTITY_IRON_GOLEM_STEP" });
        SoundManager.sounds.put("ENTITY_IRONGOLEM_STEP", new String[] { "IRONGOLEM_WALK", "ENTITY_IRON_GOLEM_STEP" });
        SoundManager.sounds.put("ENTITY_IRON_GOLEM_STEP", new String[] { "IRONGOLEM_WALK", "ENTITY_IRONGOLEM_STEP" });
        SoundManager.sounds.put("MAGMACUBE_WALK", new String[] { "ENTITY_MAGMACUBE_SQUISH", "ENTITY_MAGMA_CUBE_SQUISH" });
        SoundManager.sounds.put("ENTITY_MAGMACUBE_SQUISH", new String[] { "MAGMACUBE_WALK", "ENTITY_MAGMA_CUBE_SQUISH" });
        SoundManager.sounds.put("ENTITY_MAGMA_CUBE_SQUISH", new String[] { "MAGMACUBE_WALK", "ENTITY_MAGMACUBE_SQUISH" });
        SoundManager.sounds.put("MAGMACUBE_WALK2", new String[] { "ENTITY_MAGMACUBE_SQUISH", "ENTITY_MAGMA_CUBE_SQUISH_SMALL" });
        SoundManager.sounds.put("ENTITY_MAGMACUBE_SQUISH", new String[] { "MAGMACUBE_WALK2", "ENTITY_MAGMA_CUBE_SQUISH_SMALL" });
        SoundManager.sounds.put("ENTITY_MAGMA_CUBE_SQUISH_SMALL", new String[] { "MAGMACUBE_WALK2", "ENTITY_MAGMACUBE_SQUISH" });
        SoundManager.sounds.put("MAGMACUBE_JUMP", new String[] { "ENTITY_MAGMACUBE_JUMP", "ENTITY_MAGMA_CUBE_JUMP" });
        SoundManager.sounds.put("ENTITY_MAGMACUBE_JUMP", new String[] { "MAGMACUBE_JUMP", "ENTITY_MAGMA_CUBE_JUMP" });
        SoundManager.sounds.put("ENTITY_MAGMA_CUBE_JUMP", new String[] { "MAGMACUBE_JUMP", "ENTITY_MAGMACUBE_JUMP" });
        SoundManager.sounds.put("PIG_IDLE", new String[] { "ENTITY_PIG_AMBIENT" });
        SoundManager.sounds.put("ENTITY_PIG_AMBIENT", new String[] { "PIG_IDLE" });
        SoundManager.sounds.put("PIG_DEATH", new String[] { "ENTITY_PIG_DEATH" });
        SoundManager.sounds.put("ENTITY_PIG_DEATH", new String[] { "PIG_DEATH" });
        SoundManager.sounds.put("PIG_WALK", new String[] { "ENTITY_PIG_STEP" });
        SoundManager.sounds.put("ENTITY_PIG_STEP", new String[] { "PIG_WALK" });
        SoundManager.sounds.put("SHEEP_IDLE", new String[] { "ENTITY_SHEEP_AMBIENT" });
        SoundManager.sounds.put("ENTITY_SHEEP_AMBIENT", new String[] { "SHEEP_IDLE" });
        SoundManager.sounds.put("SHEEP_SHEAR", new String[] { "ENTITY_SHEEP_SHEAR" });
        SoundManager.sounds.put("ENTITY_SHEEP_SHEAR", new String[] { "SHEEP_SHEAR" });
        SoundManager.sounds.put("SHEEP_WALK", new String[] { "ENTITY_SHEEP_STEP" });
        SoundManager.sounds.put("ENTITY_SHEEP_STEP", new String[] { "SHEEP_WALK" });
        SoundManager.sounds.put("SILVERFISH_HIT", new String[] { "ENTITY_SILVERFISH_HURT" });
        SoundManager.sounds.put("ENTITY_SILVERFISH_HURT", new String[] { "SILVERFISH_HIT" });
        SoundManager.sounds.put("SILVERFISH_KILL", new String[] { "ENTITY_SILVERFISH_DEATH" });
        SoundManager.sounds.put("ENTITY_SILVERFISH_DEATH", new String[] { "SILVERFISH_KILL" });
        SoundManager.sounds.put("SILVERFISH_IDLE", new String[] { "ENTITY_SILVERFISH_AMBIENT" });
        SoundManager.sounds.put("ENTITY_SILVERFISH_AMBIENT", new String[] { "SILVERFISH_IDLE" });
        SoundManager.sounds.put("SILVERFISH_WALK", new String[] { "ENTITY_SILVERFISH_STEP" });
        SoundManager.sounds.put("ENTITY_SILVERFISH_STEP", new String[] { "SILVERFISH_WALK" });
        SoundManager.sounds.put("SKELETON_IDLE", new String[] { "ENTITY_SKELETON_AMBIENT" });
        SoundManager.sounds.put("ENTITY_SKELETON_AMBIENT", new String[] { "SKELETON_IDLE" });
        SoundManager.sounds.put("SKELETON_DEATH", new String[] { "ENTITY_SKELETON_DEATH" });
        SoundManager.sounds.put("ENTITY_SKELETON_DEATH", new String[] { "SKELETON_DEATH" });
        SoundManager.sounds.put("SKELETON_HURT", new String[] { "ENTITY_SKELETON_HURT" });
        SoundManager.sounds.put("ENTITY_SKELETON_HURT", new String[] { "SKELETON_HURT" });
        SoundManager.sounds.put("SKELETON_WALK", new String[] { "ENTITY_SKELETON_STEP" });
        SoundManager.sounds.put("ENTITY_SKELETON_STEP", new String[] { "SKELETON_WALK" });
        SoundManager.sounds.put("SLIME_ATTACK", new String[] { "ENTITY_SLIME_ATTACK" });
        SoundManager.sounds.put("ENTITY_SLIME_ATTACK", new String[] { "SLIME_ATTACK" });
        SoundManager.sounds.put("SLIME_WALK", new String[] { "ENTITY_SLIME_JUMP" });
        SoundManager.sounds.put("ENTITY_SLIME_JUMP", new String[] { "SLIME_WALK" });
        SoundManager.sounds.put("SLIME_WALK2", new String[] { "ENTITY_SLIME_SQUISH" });
        SoundManager.sounds.put("ENTITY_SLIME_SQUISH", new String[] { "SLIME_WALK2" });
        SoundManager.sounds.put("SPIDER_IDLE", new String[] { "ENTITY_SPIDER_AMBIENT" });
        SoundManager.sounds.put("ENTITY_SPIDER_AMBIENT", new String[] { "SPIDER_IDLE" });
        SoundManager.sounds.put("SPIDER_DEATH", new String[] { "ENTITY_SPIDER_DEATH" });
        SoundManager.sounds.put("ENTITY_SPIDER_DEATH", new String[] { "SPIDER_DEATH" });
        SoundManager.sounds.put("SPIDER_WALK", new String[] { "ENTITY_SPIDER_STEP" });
        SoundManager.sounds.put("ENTITY_SPIDER_STEP", new String[] { "SPIDER_WALK" });
        SoundManager.sounds.put("WITHER_DEATH", new String[] { "ENTITY_WITHER_DEATH" });
        SoundManager.sounds.put("ENTITY_WITHER_DEATH", new String[] { "WITHER_DEATH" });
        SoundManager.sounds.put("WITHER_HURT", new String[] { "ENTITY_WITHER_HURT" });
        SoundManager.sounds.put("ENTITY_WITHER_HURT", new String[] { "WITHER_HURT" });
        SoundManager.sounds.put("WITHER_IDLE", new String[] { "ENTITY_WITHER_AMBIENT" });
        SoundManager.sounds.put("ENTITY_WITHER_AMBIENT", new String[] { "WITHER_IDLE" });
        SoundManager.sounds.put("WITHER_SHOOT", new String[] { "ENTITY_WITHER_SHOOT" });
        SoundManager.sounds.put("ENTITY_WITHER_SHOOT", new String[] { "WITHER_SHOOT" });
        SoundManager.sounds.put("WITHER_SPAWN", new String[] { "ENTITY_WITHER_SPAWN" });
        SoundManager.sounds.put("ENTITY_WITHER_SPAWN", new String[] { "WITHER_SPAWN" });
        SoundManager.sounds.put("WOLF_BARK", new String[] { "ENTITY_WOLF_AMBIENT" });
        SoundManager.sounds.put("ENTITY_WOLF_AMBIENT", new String[] { "WOLF_BARK" });
        SoundManager.sounds.put("WOLF_DEATH", new String[] { "ENTITY_WOLF_DEATH" });
        SoundManager.sounds.put("ENTITY_WOLF_DEATH", new String[] { "WOLF_DEATH" });
        SoundManager.sounds.put("WOLF_GROWL", new String[] { "ENTITY_WOLF_GROWL" });
        SoundManager.sounds.put("ENTITY_WOLF_GROWL", new String[] { "WOLF_GROWL" });
        SoundManager.sounds.put("WOLF_HOWL", new String[] { "ENTITY_WOLF_HOWL" });
        SoundManager.sounds.put("ENTITY_WOLF_HOWL", new String[] { "WOLF_HOWL" });
        SoundManager.sounds.put("WOLF_HURT", new String[] { "ENTITY_WOLF_HURT" });
        SoundManager.sounds.put("ENTITY_WOLF_HURT", new String[] { "WOLF_HURT" });
        SoundManager.sounds.put("WOLF_PANT", new String[] { "ENTITY_WOLF_PANT" });
        SoundManager.sounds.put("ENTITY_WOLF_PANT", new String[] { "WOLF_PANT" });
        SoundManager.sounds.put("WOLF_SHAKE", new String[] { "ENTITY_WOLF_SHAKE" });
        SoundManager.sounds.put("ENTITY_WOLF_SHAKE", new String[] { "WOLF_SHAKE" });
        SoundManager.sounds.put("WOLF_WALK", new String[] { "ENTITY_WOLF_STEP" });
        SoundManager.sounds.put("ENTITY_WOLF_STEP", new String[] { "WOLF_WALK" });
        SoundManager.sounds.put("WOLF_WHINE", new String[] { "ENTITY_WOLF_WHINE" });
        SoundManager.sounds.put("ENTITY_WOLF_WHINE", new String[] { "WOLF_WHINE" });
        SoundManager.sounds.put("ZOMBIE_METAL", new String[] { "ENTITY_ZOMBIE_ATTACK_IRON_DOOR" });
        SoundManager.sounds.put("ENTITY_ZOMBIE_ATTACK_IRON_DOOR", new String[] { "ZOMBIE_METAL" });
        SoundManager.sounds.put("ZOMBIE_WOOD", new String[] { "ENTITY_ZOMBIE_ATTACK_DOOR_WOOD", "ENTITY_ZOMBIE_ATTACK_WOODEN_DOOR" });
        SoundManager.sounds.put("ENTITY_ZOMBIE_ATTACK_DOOR_WOOD", new String[] { "ZOMBIE_WOOD", "ENTITY_ZOMBIE_ATTACK_WOODEN_DOOR" });
        SoundManager.sounds.put("ENTITY_ZOMBIE_ATTACK_WOODEN_DOOR", new String[] { "ZOMBIE_WOOD", "ENTITY_ZOMBIE_ATTACK_DOOR_WOOD" });
        SoundManager.sounds.put("ZOMBIE_WOODBREAK", new String[] { "ENTITY_ZOMBIE_BREAK_DOOR_WOOD", "ENTITY_ZOMBIE_BREAK_WOODEN_DOOR" });
        SoundManager.sounds.put("ENTITY_ZOMBIE_BREAK_DOOR_WOOD", new String[] { "ZOMBIE_WOODBREAK", "ENTITY_ZOMBIE_BREAK_WOODEN_DOOR" });
        SoundManager.sounds.put("ENTITY_ZOMBIE_BREAK_WOODEN_DOOR", new String[] { "ZOMBIE_WOODBREAK", "ENTITY_ZOMBIE_BREAK_DOOR_WOOD" });
        SoundManager.sounds.put("ZOMBIE_IDLE", new String[] { "ENTITY_ZOMBIE_AMBIENT" });
        SoundManager.sounds.put("ENTITY_ZOMBIE_AMBIENT", new String[] { "ZOMBIE_IDLE" });
        SoundManager.sounds.put("ZOMBIE_DEATH", new String[] { "ENTITY_ZOMBIE_DEATH" });
        SoundManager.sounds.put("ENTITY_ZOMBIE_DEATH", new String[] { "ZOMBIE_DEATH" });
        SoundManager.sounds.put("ZOMBIE_HURT", new String[] { "ENTITY_ZOMBIE_HURT" });
        SoundManager.sounds.put("ENTITY_ZOMBIE_HURT", new String[] { "ZOMBIE_HURT" });
        SoundManager.sounds.put("ZOMBIE_INFECT", new String[] { "ENTITY_ZOMBIE_INFECT" });
        SoundManager.sounds.put("ENTITY_ZOMBIE_INFECT", new String[] { "ZOMBIE_INFECT" });
        SoundManager.sounds.put("ZOMBIE_UNFECT", new String[] { "ENTITY_ZOMBIE_VILLAGER_CONVERTED" });
        SoundManager.sounds.put("ENTITY_ZOMBIE_VILLAGER_CONVERTED", new String[] { "ZOMBIE_UNFECT" });
        SoundManager.sounds.put("ZOMBIE_REMEDY", new String[] { "ENTITY_ZOMBIE_VILLAGER_CURE" });
        SoundManager.sounds.put("ENTITY_ZOMBIE_VILLAGER_CURE", new String[] { "ZOMBIE_REMEDY" });
        SoundManager.sounds.put("ZOMBIE_WALK", new String[] { "ENTITY_ZOMBIE_STEP" });
        SoundManager.sounds.put("ENTITY_ZOMBIE_STEP", new String[] { "ZOMBIE_WALK" });
        SoundManager.sounds.put("ZOMBIE_PIG_IDLE", new String[] { "ENTITY_ZOMBIE_PIG_AMBIENT", "ENTITY_ZOMBIE_PIGMAN_AMBIENT" });
        SoundManager.sounds.put("ENTITY_ZOMBIE_PIG_AMBIENT", new String[] { "ZOMBIE_PIG_IDLE", "ENTITY_ZOMBIE_PIGMAN_AMBIENT" });
        SoundManager.sounds.put("ENTITY_ZOMBIE_PIGMAN_AMBIENT", new String[] { "ZOMBIE_PIG_IDLE", "ENTITY_ZOMBIE_PIG_AMBIENT" });
        SoundManager.sounds.put("ZOMBIE_PIG_ANGRY", new String[] { "ENTITY_ZOMBIE_PIG_ANGRY", "ENTITY_ZOMBIE_PIGMAN_ANGRY" });
        SoundManager.sounds.put("ENTITY_ZOMBIE_PIG_ANGRY", new String[] { "ZOMBIE_PIG_ANGRY", "ENTITY_ZOMBIE_PIGMAN_ANGRY" });
        SoundManager.sounds.put("ENTITY_ZOMBIE_PIGMAN_ANGRY", new String[] { "ZOMBIE_PIG_ANGRY", "ENTITY_ZOMBIE_PIG_ANGRY" });
        SoundManager.sounds.put("ZOMBIE_PIG_DEATH", new String[] { "ENTITY_ZOMBIE_PIG_DEATH", "ENTITY_ZOMBIE_PIGMAN_DEATH" });
        SoundManager.sounds.put("ENTITY_ZOMBIE_PIG_DEATH", new String[] { "ZOMBIE_PIG_DEATH", "ENTITY_ZOMBIE_PIGMAN_DEATH" });
        SoundManager.sounds.put("ENTITY_ZOMBIE_PIGMAN_DEATH", new String[] { "ZOMBIE_PIG_DEATH", "ENTITY_ZOMBIE_PIG_DEATH" });
        SoundManager.sounds.put("ZOMBIE_PIG_HURT", new String[] { "ENTITY_ZOMBIE_PIG_HURT", "ENTITY_ZOMBIE_PIGMAN_HURT" });
        SoundManager.sounds.put("ENTITY_ZOMBIE_PIG_HURT", new String[] { "ZOMBIE_PIG_HURT", "ENTITY_ZOMBIE_PIGMAN_HURT" });
        SoundManager.sounds.put("ENTITY_ZOMBIE_PIGMAN_HURT", new String[] { "ZOMBIE_PIG_HURT", "ENTITY_ZOMBIE_PIG_HURT" });
        SoundManager.sounds.put("DIG_WOOL", new String[] { "BLOCK_CLOTH_BREAK", "BLOCK_WOOL_BREAK" });
        SoundManager.sounds.put("BLOCK_CLOTH_BREAK", new String[] { "DIG_WOOL", "BLOCK_WOOL_BREAK" });
        SoundManager.sounds.put("BLOCK_WOOL_BREAK", new String[] { "DIG_WOOL", "BLOCK_CLOTH_BREAK" });
        SoundManager.sounds.put("DIG_GRASS", new String[] { "BLOCK_GRASS_BREAK" });
        SoundManager.sounds.put("BLOCK_GRASS_BREAK", new String[] { "DIG_GRASS" });
        SoundManager.sounds.put("DIG_GRAVEL", new String[] { "BLOCK_GRAVEL_BREAK" });
        SoundManager.sounds.put("BLOCK_GRAVEL_BREAK", new String[] { "DIG_GRAVEL" });
        SoundManager.sounds.put("DIG_SAND", new String[] { "BLOCK_SAND_BREAK" });
        SoundManager.sounds.put("BLOCK_SAND_BREAK", new String[] { "DIG_SAND" });
        SoundManager.sounds.put("DIG_SNOW", new String[] { "BLOCK_SNOW_BREAK" });
        SoundManager.sounds.put("BLOCK_SNOW_BREAK", new String[] { "DIG_SNOW" });
        SoundManager.sounds.put("DIG_STONE", new String[] { "BLOCK_STONE_BREAK" });
        SoundManager.sounds.put("BLOCK_STONE_BREAK", new String[] { "DIG_STONE" });
        SoundManager.sounds.put("DIG_WOOD", new String[] { "BLOCK_WOOD_BREAK" });
        SoundManager.sounds.put("BLOCK_WOOD_BREAK", new String[] { "DIG_WOOD" });
        SoundManager.sounds.put("FIREWORK_BLAST", new String[] { "ENTITY_FIREWORK_BLAST", "ENTITY_FIREWORK_ROCKET_BLAST" });
        SoundManager.sounds.put("ENTITY_FIREWORK_BLAST", new String[] { "FIREWORK_BLAST", "ENTITY_FIREWORK_ROCKET_BLAST" });
        SoundManager.sounds.put("ENTITY_FIREWORK_ROCKET_BLAST", new String[] { "FIREWORK_BLAST", "ENTITY_FIREWORK_BLAST" });
        SoundManager.sounds.put("FIREWORK_BLAST2", new String[] { "ENTITY_FIREWORK_BLAST_FAR", "ENTITY_FIREWORK_ROCKET_BLAST_FAR" });
        SoundManager.sounds.put("ENTITY_FIREWORK_BLAST_FAR", new String[] { "FIREWORK_BLAST2", "ENTITY_FIREWORK_ROCKET_BLAST_FAR" });
        SoundManager.sounds.put("ENTITY_FIREWORK_ROCKET_BLAST_FAR", new String[] { "FIREWORK_BLAST2", "ENTITY_FIREWORK_BLAST_FAR" });
        SoundManager.sounds.put("FIREWORK_LARGE_BLAST", new String[] { "ENTITY_FIREWORK_LARGE_BLAST", "ENTITY_FIREWORK_ROCKET_LARGE_BLAST" });
        SoundManager.sounds.put("ENTITY_FIREWORK_LARGE_BLAST", new String[] { "FIREWORK_LARGE_BLAST", "ENTITY_FIREWORK_ROCKET_LARGE_BLAST" });
        SoundManager.sounds.put("ENTITY_FIREWORK_ROCKET_LARGE_BLAST", new String[] { "FIREWORK_LARGE_BLAST", "ENTITY_FIREWORK_LARGE_BLAST" });
        SoundManager.sounds.put("FIREWORK_LARGE_BLAST2", new String[] { "ENTITY_FIREWORK_LARGE_BLAST_FAR", "ENTITY_FIREWORK_ROCKET_LARGE_BLAST_FAR" });
        SoundManager.sounds.put("ENTITY_FIREWORK_LARGE_BLAST_FAR", new String[] { "FIREWORK_LARGE_BLAST2", "ENTITY_FIREWORK_ROCKET_LARGE_BLAST_FAR" });
        SoundManager.sounds.put("ENTITY_FIREWORK_ROCKET_LARGE_BLAST_FAR", new String[] { "FIREWORK_LARGE_BLAST2", "ENTITY_FIREWORK_LARGE_BLAST_FAR" });
        SoundManager.sounds.put("FIREWORK_LAUNCH", new String[] { "ENTITY_FIREWORK_LAUNCH", "ENTITY_FIREWORK_ROCKET_LAUNCH" });
        SoundManager.sounds.put("ENTITY_FIREWORK_LAUNCH", new String[] { "FIREWORK_LAUNCH", "ENTITY_FIREWORK_ROCKET_LAUNCH" });
        SoundManager.sounds.put("ENTITY_FIREWORK_ROCKET_LAUNCH", new String[] { "FIREWORK_LAUNCH", "ENTITY_FIREWORK_LAUNCH" });
        SoundManager.sounds.put("FIREWORK_TWINKLE", new String[] { "ENTITY_FIREWORK_TWINKLE", "ENTITY_FIREWORK_ROCKET_TWINKLE" });
        SoundManager.sounds.put("ENTITY_FIREWORK_TWINKLE", new String[] { "FIREWORK_TWINKLE", "ENTITY_FIREWORK_ROCKET_TWINKLE" });
        SoundManager.sounds.put("ENTITY_FIREWORK_ROCKET_TWINKLE", new String[] { "FIREWORK_TWINKLE", "ENTITY_FIREWORK_TWINKLE" });
        SoundManager.sounds.put("FIREWORK_TWINKLE2", new String[] { "ENTITY_FIREWORK_TWINKLE_FAR", "ENTITY_FIREWORK_ROCKET_TWINKLE_FAR" });
        SoundManager.sounds.put("ENTITY_FIREWORK_TWINKLE_FAR", new String[] { "FIREWORK_TWINKLE2", "ENTITY_FIREWORK_ROCKET_TWINKLE_FAR" });
        SoundManager.sounds.put("ENTITY_FIREWORK_ROCKET_TWINKLE_FAR", new String[] { "FIREWORK_TWINKLE2", "ENTITY_FIREWORK_TWINKLE_FAR" });
        SoundManager.sounds.put("SUCCESSFUL_HIT", new String[] { "ENTITY_PLAYER_ATTACK_STRONG" });
        SoundManager.sounds.put("ENTITY_PLAYER_ATTACK_STRONG", new String[] { "SUCCESSFUL_HIT" });
        SoundManager.sounds.put("HORSE_ANGRY", new String[] { "ENTITY_HORSE_ANGRY" });
        SoundManager.sounds.put("ENTITY_HORSE_ANGRY", new String[] { "HORSE_ANGRY" });
        SoundManager.sounds.put("HORSE_ARMOR", new String[] { "ENTITY_HORSE_ARMOR" });
        SoundManager.sounds.put("ENTITY_HORSE_ARMOR", new String[] { "HORSE_ARMOR" });
        SoundManager.sounds.put("HORSE_BREATHE", new String[] { "ENTITY_HORSE_BREATHE" });
        SoundManager.sounds.put("ENTITY_HORSE_BREATHE", new String[] { "HORSE_BREATHE" });
        SoundManager.sounds.put("HORSE_DEATH", new String[] { "ENTITY_HORSE_DEATH" });
        SoundManager.sounds.put("ENTITY_HORSE_DEATH", new String[] { "HORSE_DEATH" });
        SoundManager.sounds.put("HORSE_GALLOP", new String[] { "ENTITY_HORSE_GALLOP" });
        SoundManager.sounds.put("ENTITY_HORSE_GALLOP", new String[] { "HORSE_GALLOP" });
        SoundManager.sounds.put("HORSE_HIT", new String[] { "ENTITY_HORSE_HURT" });
        SoundManager.sounds.put("ENTITY_HORSE_HURT", new String[] { "HORSE_HIT" });
        SoundManager.sounds.put("HORSE_IDLE", new String[] { "ENTITY_HORSE_AMBIENT" });
        SoundManager.sounds.put("ENTITY_HORSE_AMBIENT", new String[] { "HORSE_IDLE" });
        SoundManager.sounds.put("HORSE_JUMP", new String[] { "ENTITY_HORSE_JUMP" });
        SoundManager.sounds.put("ENTITY_HORSE_JUMP", new String[] { "HORSE_JUMP" });
        SoundManager.sounds.put("HORSE_LAND", new String[] { "ENTITY_HORSE_LAND" });
        SoundManager.sounds.put("ENTITY_HORSE_LAND", new String[] { "HORSE_LAND" });
        SoundManager.sounds.put("HORSE_SADDLE", new String[] { "ENTITY_HORSE_SADDLE" });
        SoundManager.sounds.put("ENTITY_HORSE_SADDLE", new String[] { "HORSE_SADDLE" });
        SoundManager.sounds.put("HORSE_SOFT", new String[] { "ENTITY_HORSE_STEP" });
        SoundManager.sounds.put("ENTITY_HORSE_STEP", new String[] { "HORSE_SOFT" });
        SoundManager.sounds.put("HORSE_WOOD", new String[] { "ENTITY_HORSE_STEP_WOOD" });
        SoundManager.sounds.put("ENTITY_HORSE_STEP_WOOD", new String[] { "HORSE_WOOD" });
        SoundManager.sounds.put("DONKEY_ANGRY", new String[] { "ENTITY_DONKEY_ANGRY" });
        SoundManager.sounds.put("ENTITY_DONKEY_ANGRY", new String[] { "DONKEY_ANGRY" });
        SoundManager.sounds.put("DONKEY_DEATH", new String[] { "ENTITY_DONKEY_DEATH" });
        SoundManager.sounds.put("ENTITY_DONKEY_DEATH", new String[] { "DONKEY_DEATH" });
        SoundManager.sounds.put("DONKEY_HIT", new String[] { "ENTITY_DONKEY_HURT" });
        SoundManager.sounds.put("ENTITY_DONKEY_HURT", new String[] { "DONKEY_HIT" });
        SoundManager.sounds.put("DONKEY_IDLE", new String[] { "ENTITY_DONKEY_AMBIENT" });
        SoundManager.sounds.put("ENTITY_DONKEY_AMBIENT", new String[] { "DONKEY_IDLE" });
        SoundManager.sounds.put("HORSE_SKELETON_DEATH", new String[] { "ENTITY_SKELETON_HORSE_DEATH" });
        SoundManager.sounds.put("ENTITY_SKELETON_HORSE_DEATH", new String[] { "HORSE_SKELETON_DEATH" });
        SoundManager.sounds.put("HORSE_SKELETON_HIT", new String[] { "ENTITY_SKELETON_HORSE_HURT" });
        SoundManager.sounds.put("ENTITY_SKELETON_HORSE_HURT", new String[] { "HORSE_SKELETON_HIT" });
        SoundManager.sounds.put("HORSE_SKELETON_IDLE", new String[] { "ENTITY_SKELETON_HORSE_AMBIENT" });
        SoundManager.sounds.put("ENTITY_SKELETON_HORSE_AMBIENT", new String[] { "HORSE_SKELETON_IDLE" });
        SoundManager.sounds.put("HORSE_ZOMBIE_DEATH", new String[] { "ENTITY_ZOMBIE_HORSE_DEATH" });
        SoundManager.sounds.put("ENTITY_ZOMBIE_HORSE_DEATH", new String[] { "HORSE_ZOMBIE_DEATH" });
        SoundManager.sounds.put("HORSE_ZOMBIE_HIT", new String[] { "ENTITY_ZOMBIE_HORSE_HURT" });
        SoundManager.sounds.put("ENTITY_ZOMBIE_HORSE_HURT", new String[] { "HORSE_ZOMBIE_HIT" });
        SoundManager.sounds.put("HORSE_ZOMBIE_IDLE", new String[] { "ENTITY_ZOMBIE_HORSE_AMBIENT" });
        SoundManager.sounds.put("ENTITY_ZOMBIE_HORSE_AMBIENT", new String[] { "HORSE_ZOMBIE_IDLE" });
        SoundManager.sounds.put("VILLAGER_DEATH", new String[] { "ENTITY_VILLAGER_DEATH" });
        SoundManager.sounds.put("ENTITY_VILLAGER_DEATH", new String[] { "VILLAGER_DEATH" });
        SoundManager.sounds.put("VILLAGER_HAGGLE", new String[] { "ENTITY_VILLAGER_TRADING", "ENTITY_VILLAGER_TRADE" });
        SoundManager.sounds.put("ENTITY_VILLAGER_TRADING", new String[] { "VILLAGER_HAGGLE", "ENTITY_VILLAGER_TRADE" });
        SoundManager.sounds.put("ENTITY_VILLAGER_TRADE", new String[] { "VILLAGER_HAGGLE", "ENTITY_VILLAGER_TRADING" });
        SoundManager.sounds.put("VILLAGER_HIT", new String[] { "ENTITY_VILLAGER_HURT" });
        SoundManager.sounds.put("ENTITY_VILLAGER_HURT", new String[] { "VILLAGER_HIT" });
        SoundManager.sounds.put("VILLAGER_IDLE", new String[] { "ENTITY_VILLAGER_AMBIENT" });
        SoundManager.sounds.put("ENTITY_VILLAGER_AMBIENT", new String[] { "VILLAGER_IDLE" });
        SoundManager.sounds.put("VILLAGER_NO", new String[] { "ENTITY_VILLAGER_NO" });
        SoundManager.sounds.put("ENTITY_VILLAGER_NO", new String[] { "VILLAGER_NO" });
        SoundManager.sounds.put("VILLAGER_YES", new String[] { "ENTITY_VILLAGER_YES" });
        SoundManager.sounds.put("ENTITY_VILLAGER_YES", new String[] { "VILLAGER_YES" });
    }
    
    public static Sound get(final String name) throws IllegalArgumentException {
        try {
            return Sound.valueOf(name);
        }
        catch (IllegalArgumentException e) {
            final String[] otherNames = SoundManager.sounds.get(name);
            if (otherNames != null) {
                final String[] array;
                final int length = (array = otherNames).length;
                int i = 0;
                while (i < length) {
                    final String otherName = array[i];
                    try {
                        return Sound.valueOf(otherName);
                    }
                    catch (IllegalArgumentException ex) {
                        ++i;
                    }
                }
            }
            throw new IllegalArgumentException();
        }
    }
}
